// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-w4NoKZG_kdyUheK8wejjZsY6zhQr1z8',
    appId: '1:49491866019:web:3c9d08bdefedc9a4dd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    authDomain: 'to-do-best-72308.firebaseapp.com',
    databaseURL: 'https://to-do-best-72308-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-best-72308.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBJ3XkCBYPSLcc4PugxjWAdeNyqfEWHM',
    appId: '1:49491866019:android:747dc0a50581b5a2dd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    databaseURL: 'https://to-do-best-72308-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-best-72308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZH3iZrSsQMygx9-XbjpSRIj_z8h7dWm4',
    appId: '1:49491866019:ios:20f1bd3ed94a3e11dd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    databaseURL: 'https://to-do-best-72308-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-best-72308.firebasestorage.app',
    androidClientId: '49491866019-k3v15lk3tlkf1kh8dtqdrthu52rjeol8.apps.googleusercontent.com',
    iosClientId: '49491866019-4ntd7fb8uc0s6trao9hq37bag1ikgcph.apps.googleusercontent.com',
    iosBundleId: 'com.example.todobestHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZH3iZrSsQMygx9-XbjpSRIj_z8h7dWm4',
    appId: '1:49491866019:ios:7fe2a59782815144dd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    databaseURL: 'https://to-do-best-72308-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-best-72308.firebasestorage.app',
    androidClientId: '49491866019-k3v15lk3tlkf1kh8dtqdrthu52rjeol8.apps.googleusercontent.com',
    iosClientId: '49491866019-4op20ipf3jjpkun2c6g587f3bjcsc57v.apps.googleusercontent.com',
    iosBundleId: 'com.example.latest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-w4NoKZG_kdyUheK8wejjZsY6zhQr1z8',
    appId: '1:49491866019:web:5f06bf89a590bbdadd2a16',
    messagingSenderId: '49491866019',
    projectId: 'to-do-best-72308',
    authDomain: 'to-do-best-72308.firebaseapp.com',
    databaseURL: 'https://to-do-best-72308-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-best-72308.firebasestorage.app',
  );
}
